<a href="https://colab.research.google.com/github/Varun-Singhal/Neural-Network/blob/master/GestureClassificationCNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import pickle 
import numpy as np
from keras.layers import Conv2D, Dense, Flatten, MaxPooling2D, Input, Flatten, Dropout, Convolution2D, Activation
from keras.models import Sequential
from tensorflow import one_hot
import tensorflow as tf
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [56]:
with open("/content/drive/My Drive/cnn.pickle","rb") as file:
  data = pickle.load(file)
print(data['data'].shape)

(147, 100, 100, 3)


In [0]:
train_x = data['data']
train_y = data['target']

In [58]:
y = one_hot(train_y, depth=3)
with tf.Session() as sess:
    y_train = sess.run(y)
y_train = y_train.reshape(147,3)
print(y_train)

[[0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0.

In [53]:
model = Sequential()
model.add(Conv2D(32,(5,5),input_shape=(100,100,3),strides=(1,1),activation='relu'))
model.add(MaxPool2D((2,2),strides=(2,2)))
model.add(Conv2D(56,(3,3),activation='relu'))
model.add(MaxPool2D((2,2),strides=(2,2)))
model.add(Conv2D(50,(3,3),activation='relu'))
model.add(MaxPool2D((2,2),strides=(2,2)))
model.add(Conv2D(48,(3,3),activation='relu'))
model.add(MaxPool2D((2,2),strides=(2,2)))
model.add(Conv2D(10,(1,1),activation='relu'))
model.add(MaxPool2D((2,2),strides=(2,2)))
model.add(Flatten())
model.add(Dense(3,activation='softmax'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_61 (Conv2D)           (None, 96, 96, 32)        2432      
_________________________________________________________________
max_pooling2d_35 (MaxPooling (None, 48, 48, 32)        0         
_________________________________________________________________
conv2d_62 (Conv2D)           (None, 46, 46, 56)        16184     
_________________________________________________________________
max_pooling2d_36 (MaxPooling (None, 23, 23, 56)        0         
_________________________________________________________________
conv2d_63 (Conv2D)           (None, 21, 21, 50)        25250     
_________________________________________________________________
max_pooling2d_37 (MaxPooling (None, 10, 10, 50)        0         
_________________________________________________________________
conv2d_64 (Conv2D)           (None, 8, 8, 48)          21648     
__________

In [63]:
model = Sequential()

 
model.add(Convolution2D(filters=32,kernel_size=(3,3),padding='same',  activation='relu', input_shape=(100,100,3)))
model.add(Convolution2D(filters=35, kernel_size=(3,3), activation='relu'))
model.add(MaxPooling2D(pool_size=(1,1)))
model.add(Convolution2D(filters=40, kernel_size=(3,3),padding='same', activation='relu'))
model.add(Convolution2D(filters=43, kernel_size=(3,3), activation='relu'))
model.add(MaxPooling2D(pool_size=(3,3)))
#model.add(Convolution2D(10, 26))
model.add(Flatten())
model.add(Dense(3))
model.add(Activation('softmax'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_76 (Conv2D)           (None, 100, 100, 32)      896       
_________________________________________________________________
conv2d_77 (Conv2D)           (None, 98, 98, 35)        10115     
_________________________________________________________________
max_pooling2d_44 (MaxPooling (None, 98, 98, 35)        0         
_________________________________________________________________
conv2d_78 (Conv2D)           (None, 98, 98, 40)        12640     
_________________________________________________________________
conv2d_79 (Conv2D)           (None, 96, 96, 43)        15523     
_________________________________________________________________
max_pooling2d_45 (MaxPooling (None, 32, 32, 43)        0         
_________________________________________________________________
flatten_12 (Flatten)         (None, 44032)             0         
__________

In [77]:
model = Sequential()
model.add(Convolution2D(32,(5,5),input_shape=(100,100,3),activation='relu'))
model.add(MaxPooling2D((3,3),strides=(2,2)))
model.add(Convolution2D(15,(5,5),activation='relu'))
model.add(MaxPooling2D((3,3),strides=(2,2)))
model.add(Convolution2D(10,(1,1),activation='relu'))
model.add(Flatten())
model.add(Dense(3,activation='softmax'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_105 (Conv2D)          (None, 96, 96, 32)        2432      
_________________________________________________________________
max_pooling2d_61 (MaxPooling (None, 47, 47, 32)        0         
_________________________________________________________________
conv2d_106 (Conv2D)          (None, 43, 43, 15)        12015     
_________________________________________________________________
max_pooling2d_62 (MaxPooling (None, 21, 21, 15)        0         
_________________________________________________________________
conv2d_107 (Conv2D)          (None, 21, 21, 10)        160       
_________________________________________________________________
flatten_19 (Flatten)         (None, 4410)              0         
_________________________________________________________________
dense_23 (Dense)             (None, 3)                 13233     
Total para

In [0]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [79]:
model.fit(train_x,y_train,epochs=10)

Epoch 1/10
147/147 [==============================] - 4s 30ms/step - loss: 5.3727 - acc: 0.3333
Epoch 2/10
147/147 [==============================] - 4s 24ms/step - loss: 5.3727 - acc: 0.3333
Epoch 3/10
147/147 [==============================] - 4s 24ms/step - loss: 5.3727 - acc: 0.3333
Epoch 4/10
147/147 [==============================] - 4s 24ms/step - loss: 5.3727 - acc: 0.3333
Epoch 5/10
147/147 [==============================] - 4s 24ms/step - loss: 5.3727 - acc: 0.3333
Epoch 6/10
147/147 [==============================] - 3s 24ms/step - loss: 5.3727 - acc: 0.3333
Epoch 7/10
147/147 [==============================] - 4s 24ms/step - loss: 5.3727 - acc: 0.3333
Epoch 8/10
147/147 [==============================] - 3s 24ms/step - loss: 5.3727 - acc: 0.3333
Epoch 9/10
147/147 [==============================] - 3s 24ms/step - loss: 5.3727 - acc: 0.3333
Epoch 10/10
147/147 [==============================] - 3s 24ms/step - loss: 5.3727 - acc: 0.3333
